// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efiyvywqghvjcvzecqid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmaXl2eXdxZ2h2amN2emVjcWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTY4ODgsImV4cCI6MjA2NzczMjg4OH0.kfc8tmnvqnTT8E9bZXtWGEfQokFNmmHqqPJC1PFeJKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});